### ISSUE TITLE
"Compact" wishlist entries too large when using this extension

### ISSUE THREAD

**Issue by AlJoelson** [cptpiepmatz/great-on-deck-search#18]
Hey, great extension! Love your work. _Quick_ bug report. When using the extension and viewing a wishlist set to the **"compact" view**, each entry is much too large. I've been sure to try with all other extensions that might conflict (like Augmented Steam) disabled. Here are some screenshots:

### Extension off:

![wishlist1](https://user-images.githubusercontent.com/6069951/212544066-aa8a9449-56eb-45a9-ae6e-c035f3da7693.png)

### Extension on:

![wishlist2](https://user-images.githubusercontent.com/6069951/212544070-ecf4d709-6d5b-40d7-9e04-a3ec2406211d.png)

**Comment by cptpiepmatz** [comment]
Oh man, I hate that view.

I'll see what I can do about it.

**Comment by AlJoelson** [comment]
Thanks for that, [cptpiepmatz](https://github.com/cptpiepmatz)! I suppose if I cut down my Wishlist a little I'd stop using the compact view, haha.

**Comment by cptpiepmatz** [comment]
It may take up to a few days until the extension updates go public in the web stores.
