### ISSUE TITLE
"Show Steam Deck Verifications Badges" option not working in full game page

### ISSUE THREAD

**Issue by innovaciones** [cptpiepmatz/great-on-deck-search#22]
Hello, thank you for making this nice extension, works pretty good except one little bug, the Steam Deck Verification info is not showing inside the full game page, I have all the options from the extension enabled so my guess is that Steam changed some code in the full game page, it works fine when I search for a game the list view shows the Steam Deck Verifications info correctly.

**Comment by cptpiepmatz** [comment]
Can you send me the page url, the browsers you're using and maybe a screenshot how it looks for you?

I checked the game page of [Portal 2](https://store.steampowered.com/app/620/Portal_2/) and I can clearly see the verification info. <br>It is the default verfication info just pulled a bit higher so you can find it more easily:
![image](https://github.com/cptpiepmatz/great-on-deck-search/assets/3590829/2d947d1d-956e-42c4-b43d-de11f831ccae)

**Comment by cptpiepmatz** [comment]
@innovaciones ?

**Comment by innovaciones** [comment]
Hello, sorry for the delay I missed the notification. I tried with the same game Portal 2 and still doesn't show the Steam Deck compatibility info, here is a screenshot from my browser:

<img width="1015" alt="portal-2" src="https://github.com/cptpiepmatz/great-on-deck-search/assets/7781056/4bd12784-6087-43ca-977e-98e6c4183a5e">

I'm using Google Chrome 114.0.5735.198 (Build oficial) (x86_64) on macOS 13.4 Ventura

Let me know if I can help you debug the problem using Chrome DevTools

**Comment by cptpiepmatz** [comment]
@innovaciones I'm using
```js
document.querySelector(`[data-featuretarget="deck-verified-results"]`)
```
to find the verification element. If you put this line in your console, what is returned?
It should look like this:
![image](https://github.com/cptpiepmatz/great-on-deck-search/assets/3590829/ed1f0e35-27f8-42e3-84cf-970e768d6c0e)

**Comment by innovaciones** [comment]
I'm getting a null

<img width="516" alt="null" src="https://github.com/cptpiepmatz/great-on-deck-search/assets/7781056/78ea6ca9-505c-40be-ae13-1882eb6ba9c5">

**Comment by cptpiepmatz** [comment]
That explains why the extension isn't working for you. It only grabs that item and puts it higher up. Is the Steam Deck available in your country?

**Comment by innovaciones** [comment]
No officially, so I guess that's the problem, I tried using a private window with a vpn from USA and now I can see the Steam Deck compatibility info, I guess there is not a workaround for this, the page is served by location using IP

**Comment by cptpiepmatz** [comment]
It would be possible to render at least something.
If no verification is found, it could check it manually and place a clone of that element.

**Comment by cptpiepmatz** [comment]
The next release will contain a workaround. When Steam does not send the HTML element I'm modifying, a new one will be created at its place. The created element is not as great as the one Steam provides but at least you can see the status.

In d869a764b104f590b8db40ff57e3f78377934d40 this is implemented.

So [v1.4.0](https://github.com/cptpiepmatz/great-on-deck-search/releases/tag/v1.4.0%2Bchrome) will have this. You can either try to install the `.crx` file or just wait until the webstore updates. I would consider simply waiting, usually the update doesn't take too long.

**Comment by innovaciones** [comment]
Thank you for the fast update 🙌🏻

**Comment by cptpiepmatz** [comment]
You're welcome.
Btw you can see the version you have installed here:
![image](https://github.com/cptpiepmatz/great-on-deck-search/assets/3590829/5b791c5f-e5a9-4405-80d4-dea38ac6c4a2)

**Comment by innovaciones** [comment]
I confirm that version 1.4.0 is now showing Steam Deck Compatibility info for my country, thank you!!

<img width="667" alt="screen" src="https://github.com/cptpiepmatz/great-on-deck-search/assets/7781056/44d92fa1-9947-4d3f-90f9-b0fd0c0afd21">
