### ISSUE TITLE
Frontpage not working

### ISSUE THREAD

**Issue by alcroito** [cptpiepmatz/great-on-deck-search#23]
Hi,

The front page additions don't seem to be added. Is it related to the summer sale?
Tried with both latest Chrome 114 and latest Firefox 115.

It also doesn't work for category pages, although not sure if that counts as searches
https://store.steampowered.com/category/action/

It does work for actual search pages like
https://store.steampowered.com/search/?term=civilization

**Comment by cptpiepmatz** [comment]
Yeah this is because of the sale. It is hard to update the extension for every sale. When the sale is over it should work again.

**Comment by cptpiepmatz** [comment]
The sale is over, the plugins works again on the default store front.
