### ISSUE TITLE
Icons missing on App Page

### ISSUE THREAD

**Issue by pchristod** [cptpiepmatz/great-on-deck-search#24]
Hi,

similiar to https://github.com/cptpiepmatz/great-on-deck-search/issues/20 the Icons for ProtonDB and SDHQ are not showing when Augmented Steam Extension is installed as well. I checked the settings and I can't see any toggle which would interfere with your addon tbh. Disabling Augmented Steam fixes that issue
![Unbenannt](https://github.com/cptpiepmatz/great-on-deck-search/assets/17931739/0af352e0-554d-4dcd-be26-b455db8fdfd5)

**Comment by cptpiepmatz** [comment]
@pchristod Augmented Steam defined a css setting to hide images for the nav buttons. Not considering other extensions, how rude. 😑

I defined this setting specifically in my css now to fix this, will be in the next update as soon the stores update the package.

Btw, this is not similar to #20, there is a spacing issue which I'm not really sure how to fix yet.

**Comment by pchristod** [comment]
Ah I see, my bad, sorry. I thought it's similar because the extension combo is the same. 
Yeah, to be fair your extension works perfectly fine, it's just the combination with Augmented that doesn't. So not really your fault. Which is why I really appreciate you fixing this when you didn't have to necessarily, thank you :)

**Comment by cptpiepmatz** [comment]
No biggie, it just annoys me that other extension work like no other extensions are installed. The fix is uploaded to the stores will probably avaible in the next 24 hours.

**Comment by pchristod** [comment]
@cptpiepmatz Thanks, received the update, it's working better now :) Just gotta ask: When hovering over the Icon the box will get smaller and the icon will be missing again. Is this a limitation/intended behaviour? Seems like two boxes are somehow overlapping but only if the mouse is hovering over the button/you are about to click it.
![Unbenannt](https://github.com/cptpiepmatz/great-on-deck-search/assets/17931739/fa5a136a-5eb1-4b27-8c84-9c6b3f8299af)

Grüße ;)

**Comment by cptpiepmatz** [comment]
Ah shoot, did not fully test that. I see what I can do.

**Comment by cptpiepmatz** [comment]
I got it fixed in 88f38d07040e5c091d2d6367a0486fa8355266a1.

**Comment by pchristod** [comment]
Sounds great, thank you so much 😄
