### ISSUE TITLE
Add badges to the discovery list

### ISSUE THREAD

**Issue by BardoInsano** [cptpiepmatz/great-on-deck-search#25]
Hello!
I would like to request badges to be add to the discovery list pages. Honestly i don't know if it doesn't work, or if it is cut by other contents. This is a function that i use a lot to find new indie titles.
Thanks!

![image](https://github.com/cptpiepmatz/great-on-deck-search/assets/73143894/49690737-79c0-4077-99fd-d7557e8375a5)
![image](https://github.com/cptpiepmatz/great-on-deck-search/assets/73143894/88ece004-f2d9-41dd-b57d-85dcce9a32c2)

**Comment by cptpiepmatz** [comment]
Since the discovery list just shows some more data on app pages, the extension works as intended. 

The game you're showing simply has no entry for the deck verification nor ProtonDB entry. If I have no info, I cannot show relevant data.
