### ISSUE TITLE
Add badges to the "Special offers"

### ISSUE THREAD

**Issue by BardoInsano** [cptpiepmatz/great-on-deck-search#26]
Hello again!
Due to size limits i don't know if it's possible, but i would like to see the badges on the special offer banners, I believe that in the banner itself would not be possible, but maybe on the hover box that is shown since it's size increase when friends have the game / wishlisted the game.
Thanks again!

![image](https://github.com/cptpiepmatz/great-on-deck-search/assets/73143894/9a233c42-d9c2-43db-abef-65630e73cd14)

**Comment by cptpiepmatz** [comment]
I think I know how I could achieve this. Could you please provide where do you think would the information be placed best?

@BardoInsano

**Comment by BardoInsano** [comment]
Initialy i think that it to appear ont he main banner would be good, however since there is "half-height" banners maybe it would get too poluted depending on the sizes.

Inside de "tooltip" after the reviews maybe would be good so it can show on every game without covering the banner

**Comment by cptpiepmatz** [comment]
I see what I can do, hopefully the hover boxes are not pre-sized but rather calculated on the fly.
