### ISSUE TITLE
Enable 'ProtonDB' status on 'Profile' pages (Games List & Wish List)

### ISSUE THREAD

**Issue by Doshin108** [cptpiepmatz/great-on-deck-search#4]
## Example Profile Pages 
Games List:   https://steamcommunity.com/id/JohnnyBlocks_/games
Wish List:  https://store.steampowered.com/wishlist/id/JohnnyBlocks_/

## Expected Result
ProtonDB Status will show next to the games in list view
Example: https://store.steampowered.com/search/?filter=topsellers

## Comments
This is an exceptional implementation of ProtonDB status in the Steam store.  

One of the places I would love to see this implemented is the Games and Wish list (more the games list).
As a veteran steam user, I've loaded my library with the most amazing games as well as shovels full of trash games I got for free.  When time comes to play a game on the deck, it would be really great to view my game catalog and some how see what is good on the deck.

**Comment by cptpiepmatz** [comment]
I'm struggling to find a nice location to put the app information. Could you provide me with some imagery of what you're maybe imagining?

**Comment by Doshin108** [comment]
I envision it falling into the div elements as in these mockups.   Note these are photoshop and not the actual game ratings.

![New Project (2)](https://user-images.githubusercontent.com/3034349/178606168-d5b5208c-495a-4651-b9ab-08eece8c536a.png)
![New Project (3)](https://user-images.githubusercontent.com/3034349/178609548-d0a1a068-f9e8-4356-b183-7b79ae0dbc00.png)

**Comment by cptpiepmatz** [comment]
yeah, that's probably the best way, I'll probably need to scale up the icons on the games list
