### ISSUE TITLE
Compatibility with SteamDB Extension (SteamDB Blocking ProtonDB Rating)

### ISSUE THREAD

**Issue by Doshin108** [cptpiepmatz/great-on-deck-search#7]
When using the SteamDB chrome extension along with the 'great on deck' extension, it causes the ProtonDB result to be hidden in game detail page.

Example:  https://store.steampowered.com/app/632470/Disco_Elysium__The_Final_Cut/

Left side is correct.
Right side is with both extensions enabled.

![steamdb](https://user-images.githubusercontent.com/3034349/178610229-6bfb0228-960a-48b6-b01c-385c61d33f46.png)

**Comment by cptpiepmatz** [comment]
In #6 I already saw this issue and fixed it, It's not currently updated in the web stores but you could try it out if you pull the current `main` branch.
